# Generated by Django 5.1.6 on 2026-08-30 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('critical', 'حرج'), ('success', 'نجاح'), ('info', 'معلومة')], max_length=16, verbose_name='المستوى')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('detail', models.CharField(blank=True, max_length=300, verbose_name='التفاصيل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='أُنشئ في')),
            ],
            options={
                'verbose_name': 'تنبيه',
                'verbose_name_plural': 'التنبيهات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(max_length=16, verbose_name='اليوم')),
                ('volume', models.PositiveIntegerField(verbose_name='الحجم')),
                ('highlight', models.BooleanField(default=False, verbose_name='تمييز')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'حجم توريد يومي',
                'verbose_name_plural': 'أحجام التوريد اليومية',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=40, unique=True, verbose_name='رمز المنتج')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='سعر الوحدة')),
                ('category', models.CharField(blank=True, max_length=80, verbose_name='التصنيف')),
            ],
            options={
                'verbose_name': 'منتج',
                'verbose_name_plural': 'المنتجات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='الرمز')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('initials', models.CharField(blank=True, max_length=4, verbose_name='الاختصار')),
                ('contact_name', models.CharField(blank=True, max_length=120, verbose_name='جهة الاتصال')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد')),
            ],
            options={
                'verbose_name': 'مورد',
                'verbose_name_plural': 'الموردون',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, verbose_name='الرمز')),
                ('name', models.CharField(max_length=120, verbose_name='الاسم')),
                ('city', models.CharField(max_length=80, verbose_name='المدينة')),
                ('capacity_percent', models.PositiveSmallIntegerField(default=0, verbose_name='نسبة الإشغال')),
            ],
            options={
                'verbose_name': 'مستودع',
                'verbose_name_plural': 'المستودعات',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='SupplyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32, unique=True, verbose_name='رقم الطلب')),
                ('priority', models.CharField(choices=[('high', 'عالية'), ('medium', 'متوسطة'), ('low', 'منخفضة')], default='medium', max_length=16, verbose_name='الأولوية')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('approved', 'معتمد'), ('sent', 'تم الإرسال'), ('preparing', 'قيد التجهيز'), ('in_transit', 'قيد النقل'), ('received', 'تم الاستلام'), ('delayed', 'متأخر')], default='pending', max_length=16, verbose_name='الحالة')),
                ('destination', models.CharField(blank=True, max_length=200, verbose_name='جهة الاستلام')),
                ('destination_address', models.CharField(blank=True, max_length=300, verbose_name='العنوان')),
                ('zone', models.CharField(blank=True, max_length=40, verbose_name='المنطقة')),
                ('aisle', models.CharField(blank=True, max_length=40, verbose_name='الممر')),
                ('bin_code', models.CharField(blank=True, max_length=40, verbose_name='الحاوية')),
                ('placed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإنشاء')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الشحن')),
                ('eta', models.DateField(blank=True, null=True, verbose_name='الوصول المتوقع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='أُنشئ في')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='portal.supplier', verbose_name='المورد')),
            ],
            options={
                'verbose_name': 'طلب توريد',
                'verbose_name_plural': 'طلبات التوريد',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='الكمية')),
                ('item_status', models.CharField(default='معبأ', max_length=40, verbose_name='حالة العنصر')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='request_items', to='portal.product', verbose_name='المنتج')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='portal.supplyrequest', verbose_name='الطلب')),
            ],
            options={
                'verbose_name': 'عنصر طلب',
                'verbose_name_plural': 'عناصر الطلب',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='الهاتف')),
                ('role', models.CharField(default='مدير مشتريات', max_length=80, verbose_name='الدور')),
                ('branch', models.CharField(default='فرع دبي الرئيسي', max_length=120, verbose_name='الفرع')),
                ('timezone_name', models.CharField(default='GST', max_length=80, verbose_name='المنطقة الزمنية')),
                ('language', models.CharField(default='ar', max_length=16, verbose_name='اللغة')),
                ('photo', models.ImageField(blank=True, upload_to='profiles/', verbose_name='الصورة')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ملف شخصي',
                'verbose_name_plural': 'الملفات الشخصية',
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32, unique=True, verbose_name='رقم الشحنة')),
                ('title', models.CharField(max_length=200, verbose_name='الوصف')),
                ('pallets', models.PositiveIntegerField(verbose_name='عدد البليت')),
                ('scheduled_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الجدولة')),
                ('scheduled_hour', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='الساعة')),
                ('status', models.CharField(choices=[('unscheduled', 'غير مجدول'), ('pending', 'قيد الانتظار'), ('confirmed', 'مؤكد'), ('conflict', 'تعارض')], default='unscheduled', max_length=16, verbose_name='الحالة')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='portal.warehouse', verbose_name='المستودع')),
            ],
            options={
                'verbose_name': 'شحنة',
                'verbose_name_plural': 'الشحنات',
                'ordering': ['scheduled_hour', 'number'],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='الكمية')),
                ('min_quantity', models.PositiveIntegerField(default=0, verbose_name='الحد الأدنى')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='portal.product', verbose_name='المنتج')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='portal.warehouse', verbose_name='المستودع')),
            ],
            options={
                'verbose_name': 'صنف مخزون',
                'verbose_name_plural': 'المخزون',
                'unique_together': {('warehouse', 'product')},
            },
        ),
    ]
