# Generated by Django 5.1.6 on 2026-08-30 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplyrequest',
            name='attachment',
            field=models.FileField(blank=True, upload_to='requests/', verbose_name='الملف'),
        ),
    ]
