# Generated by Django 5.1.6 on 2026-08-30 22:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_request_attachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplyrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'طلب شراء', 'verbose_name_plural': 'طلبات الشراء'},
        ),
        migrations.AddField(
            model_name='supplyrequest',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_requests', to=settings.AUTH_USER_MODEL, verbose_name='دائرة المشتريات'),
        ),
        migrations.AddField(
            model_name='supplyrequest',
            name='sent_to_supplier_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='أُرسل للمورد'),
        ),
        migrations.AddField(
            model_name='supplyrequest',
            name='sent_to_warehouse_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='أُرسل للمستودع'),
        ),
        migrations.AddField(
            model_name='supplyrequest',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_requests', to='portal.warehouse', verbose_name='المستودع'),
        ),
        migrations.CreateModel(
            name='RequestFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='purchase_orders/', verbose_name='الملف')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='portal.supplyrequest', verbose_name='الطلب')),
            ],
            options={
                'verbose_name': 'ملف طلب شراء',
                'verbose_name_plural': 'ملفات طلب الشراء',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
