# Generated by Django 5.1.6 on 2026-08-31 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_purchase_routing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='رقم القسم')),
                ('name', models.CharField(max_length=120, verbose_name='اسم القسم')),
            ],
            options={
                'verbose_name': 'قسم',
                'verbose_name_plural': 'الأقسام',
                'ordering': ['code'],
            },
        ),
        migrations.AlterModelOptions(
            name='requestfile',
            options={'ordering': ['uploaded_at'], 'verbose_name': 'ملف طلب توريد', 'verbose_name_plural': 'ملفات طلب التوريد'},
        ),
        migrations.AlterModelOptions(
            name='supplyrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'طلب توريد', 'verbose_name_plural': 'طلبات التوريد'},
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='city',
            field=models.CharField(blank=True, max_length=80, verbose_name='المدينة'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='code',
            field=models.CharField(max_length=32, unique=True, verbose_name='رقم المستودع'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='name',
            field=models.CharField(max_length=120, verbose_name='اسم المستودع'),
        ),
    ]
